import type { LocationFacility } from './types';

export const demoFacilities: LocationFacility[] = [
  // --- Hospitals / ERs ---
  {
    id: 'loc-1',
    name: 'Grand River Hospital ER',
    type: 'hospital',
    latitude: 43.4516,
    longitude: -80.5052,
    address: '835 King St W, Kitchener',
    hours: '24/7',
    isOpen: true,
    waitMinutes: 120,
    services: ['Emergency care', 'Trauma', 'Imaging', 'Lab work', 'Pediatric ER'],
    isFree: true,
    phone: '519-749-4300',
    reports: [
      {
        id: 'rpt-1',
        facilityId: 'loc-1',
        reporterType: 'visitor',
        message: 'Wait was about 2 hours for non-urgent. Triage was quick though.',
        createdAt: '2026-03-14T08:30:00',
      },
      {
        id: 'rpt-2',
        facilityId: 'loc-1',
        reporterType: 'medical-professional',
        message: 'High volume tonight. Expect longer waits for CTAS 4-5.',
        strainLevel: 'high',
        waitTimeUpdate: 150,
        createdAt: '2026-03-14T02:15:00',
      },
    ],
  },
  {
    id: 'loc-2',
    name: "St. Mary's General Hospital ER",
    type: 'hospital',
    latitude: 43.4372,
    longitude: -80.4865,
    address: "911 Queen's Blvd, Kitchener",
    hours: '24/7',
    isOpen: true,
    waitMinutes: 95,
    services: ['Emergency care', 'Cardiac care', 'Imaging', 'Mental health crisis'],
    isFree: true,
    phone: '519-744-3311',
    reports: [
      {
        id: 'rpt-3',
        facilityId: 'loc-2',
        reporterType: 'visitor',
        message: 'Shorter wait than Grand River right now. Got seen in about 1.5 hours.',
        createdAt: '2026-03-14T10:00:00',
      },
    ],
  },
  {
    id: 'loc-3',
    name: 'Cambridge Memorial Hospital ER',
    type: 'hospital',
    latitude: 43.3616,
    longitude: -80.3144,
    address: '700 Coronation Blvd, Cambridge',
    hours: '24/7',
    isOpen: true,
    waitMinutes: 75,
    services: ['Emergency care', 'Imaging', 'Lab work'],
    isFree: true,
    phone: '519-621-2330',
    reports: [],
  },

  // --- Walk-in Clinics ---
  {
    id: 'loc-4',
    name: 'Kitchener Walk-In Clinic',
    type: 'walk-in',
    latitude: 43.4350,
    longitude: -80.5100,
    address: '525 Highland Rd W, Kitchener',
    hours: '8 AM – 8 PM',
    isOpen: true,
    closingTime: '8:00 PM',
    waitMinutes: 25,
    services: ['General assessment', 'Prescriptions', 'Blood work on-site'],
    isFree: true,
    reports: [
      {
        id: 'rpt-4',
        facilityId: 'loc-4',
        reporterType: 'visitor',
        message: 'Quick visit today, only waited 20 minutes.',
        createdAt: '2026-03-14T11:30:00',
      },
    ],
  },
  {
    id: 'loc-5',
    name: 'Waterloo Walk-In Medical Centre',
    type: 'walk-in',
    latitude: 43.4680,
    longitude: -80.5250,
    address: '170 University Ave W, Waterloo',
    hours: '9 AM – 5 PM',
    isOpen: true,
    closingTime: '5:00 PM',
    waitMinutes: 35,
    services: ['General assessment', 'Prescriptions', 'Referrals'],
    isFree: true,
    reports: [],
  },
  {
    id: 'loc-6',
    name: 'UWaterloo Health Services',
    type: 'walk-in',
    latitude: 43.4723,
    longitude: -80.5449,
    address: 'SLC Building, Room 2040, Waterloo',
    hours: '9 AM – 4:30 PM',
    isOpen: true,
    closingTime: '4:30 PM',
    waitMinutes: 40,
    services: ['Student care', 'Mental health', 'Referrals', 'Immunizations'],
    isFree: true,
    reports: [],
  },

  // --- Urgent Care ---
  {
    id: 'loc-7',
    name: 'Grand River Urgent Care',
    type: 'urgent-care',
    latitude: 43.4820,
    longitude: -80.5460,
    address: '405 The Boardwalk, Waterloo',
    hours: '10 AM – 10 PM',
    isOpen: true,
    closingTime: '10:00 PM',
    waitMinutes: 45,
    services: ['Urgent assessment', 'X-ray', 'Stitches', 'Prescriptions'],
    isFree: true,
    reports: [
      {
        id: 'rpt-5',
        facilityId: 'loc-7',
        reporterType: 'medical-professional',
        message: 'Moderate volume. Average wait around 40-50 min.',
        strainLevel: 'moderate',
        createdAt: '2026-03-14T14:00:00',
      },
    ],
  },

  // --- Community Centres ---
  {
    id: 'loc-8',
    name: 'The Working Centre',
    type: 'community-centre',
    latitude: 43.4510,
    longitude: -80.4920,
    address: '58 Queen St S, Kitchener',
    hours: '9 AM – 5 PM',
    isOpen: true,
    closingTime: '5:00 PM',
    services: ['Job search support', 'Computer access', 'Community kitchen', 'Affordable housing help'],
    isFree: true,
    phone: '519-743-1151',
    resources: [
      { id: 'res-1', name: 'Community kitchen meals', category: 'food', inStock: true, donationNeeded: false },
      { id: 'res-2', name: 'Winter clothing', category: 'clothing', inStock: true, donationNeeded: false },
      { id: 'res-3', name: 'Hygiene kits', category: 'hygiene', inStock: false, donationNeeded: true },
      { id: 'res-4', name: 'Resume printing', category: 'other', inStock: true, donationNeeded: false },
    ],
    reports: [],
  },
  {
    id: 'loc-9',
    name: 'House of Friendship',
    type: 'community-centre',
    latitude: 43.4480,
    longitude: -80.4900,
    address: '51 Charles St E, Kitchener',
    hours: '8:30 AM – 4:30 PM',
    isOpen: true,
    closingTime: '4:30 PM',
    services: ['Food bank', 'Emergency shelter referrals', 'Addiction services', 'Community meals'],
    isFree: true,
    phone: '519-742-8327',
    resources: [
      { id: 'res-5', name: 'Food bank hampers', category: 'food', inStock: true, donationNeeded: false },
      { id: 'res-6', name: 'Canned goods', category: 'food', inStock: false, donationNeeded: true },
      { id: 'res-7', name: 'Baby formula & diapers', category: 'other', inStock: false, donationNeeded: true },
      { id: 'res-8', name: 'Personal hygiene items', category: 'hygiene', inStock: true, donationNeeded: false },
      { id: 'res-9', name: 'Warm blankets', category: 'clothing', inStock: false, donationNeeded: true },
    ],
    reports: [
      {
        id: 'rpt-6',
        facilityId: 'loc-9',
        reporterType: 'visitor',
        message: 'Food bank open today. Running low on canned goods and baby supplies.',
        createdAt: '2026-03-14T09:00:00',
      },
    ],
  },
  {
    id: 'loc-10',
    name: 'KW Multicultural Centre',
    type: 'community-centre',
    latitude: 43.4540,
    longitude: -80.4940,
    address: '102 King St W, Kitchener',
    hours: '9 AM – 5 PM',
    isOpen: true,
    closingTime: '5:00 PM',
    services: ['Settlement services', 'Language classes', 'Employment support', 'Translation services'],
    isFree: true,
    phone: '519-745-2531',
    resources: [
      { id: 'res-10', name: 'Language class materials', category: 'other', inStock: true, donationNeeded: false },
      { id: 'res-11', name: 'Welcome kits for newcomers', category: 'other', inStock: true, donationNeeded: false },
    ],
    reports: [],
  },

  // --- Wellness Centres ---
  {
    id: 'loc-11',
    name: 'YMCA of Three Rivers',
    type: 'wellness-centre',
    latitude: 43.4560,
    longitude: -80.4970,
    address: '250 King St W, Kitchener',
    hours: '6 AM – 10 PM',
    isOpen: true,
    closingTime: '10:00 PM',
    services: ['Fitness programs', 'Swimming', 'Youth programs', 'Childcare', 'Community wellness'],
    isFree: false,
    phone: '519-743-5201',
    resources: [
      { id: 'res-12', name: 'Subsidized memberships', category: 'other', inStock: true, donationNeeded: false },
      { id: 'res-13', name: 'Free youth programs', category: 'other', inStock: true, donationNeeded: false },
    ],
    reports: [],
  },
  {
    id: 'loc-12',
    name: 'Langs Community Health Centre',
    type: 'wellness-centre',
    latitude: 43.3890,
    longitude: -80.3700,
    address: '1145 Concession Rd, Cambridge',
    hours: '8:30 AM – 8 PM',
    isOpen: true,
    closingTime: '8:00 PM',
    services: ['Primary care', 'Mental health counselling', 'Diabetes education', 'Prenatal care', 'Dietitian'],
    isFree: true,
    phone: '519-653-1470',
    resources: [
      { id: 'res-14', name: 'Mental health counselling slots', category: 'mental-health', inStock: true, donationNeeded: false },
      { id: 'res-15', name: 'Diabetes supplies', category: 'medical', inStock: true, donationNeeded: false },
      { id: 'res-16', name: 'Prenatal vitamins', category: 'medical', inStock: false, donationNeeded: true },
    ],
    reports: [],
  },
  {
    id: 'loc-13',
    name: 'KW Counselling Services',
    type: 'wellness-centre',
    latitude: 43.4505,
    longitude: -80.4880,
    address: '480 Charles St E, Kitchener',
    hours: '9 AM – 9 PM',
    isOpen: true,
    closingTime: '9:00 PM',
    services: ['Individual counselling', 'Family therapy', 'Group therapy', 'Crisis support', 'Sliding scale fees'],
    isFree: false,
    phone: '519-884-0000',
    resources: [
      { id: 'res-17', name: 'Sliding scale therapy slots', category: 'mental-health', inStock: true, donationNeeded: false },
      { id: 'res-18', name: 'Free crisis walk-in sessions', category: 'mental-health', inStock: true, donationNeeded: false },
    ],
    reports: [],
  },
  {
    id: 'loc-14',
    name: 'Reception House Waterloo Region',
    type: 'wellness-centre',
    latitude: 43.4400,
    longitude: -80.4850,
    address: '63 Allen St E, Waterloo',
    hours: '9 AM – 5 PM',
    isOpen: true,
    closingTime: '5:00 PM',
    services: ['Refugee settlement', 'Health navigation', 'Housing support', 'Orientation programs'],
    isFree: true,
    phone: '519-743-2397',
    resources: [
      { id: 'res-19', name: 'Housing assistance', category: 'housing', inStock: true, donationNeeded: false },
      { id: 'res-20', name: 'Medical supply kits', category: 'medical', inStock: false, donationNeeded: true },
      { id: 'res-21', name: 'Winter clothing donations', category: 'clothing', inStock: false, donationNeeded: true },
    ],
    reports: [
      {
        id: 'rpt-7',
        facilityId: 'loc-14',
        reporterType: 'visitor',
        message: 'Currently in need of winter clothing and medical supplies. Great staff.',
        createdAt: '2026-03-13T15:00:00',
      },
    ],
  },

  // --- Telehealth ---
  {
    id: 'loc-15',
    name: 'Maple Telehealth',
    type: 'telehealth',
    latitude: 43.4643,
    longitude: -80.5204,
    address: 'Online',
    hours: '24/7',
    isOpen: true,
    waitMinutes: 8,
    services: ['Video consult', 'Prescriptions', 'Specialist referral', 'Mental health'],
    isFree: false,
    reports: [],
  },
];
