import type { LocationFacility } from './types';

export const demoFacilities: LocationFacility[] = [
  // --- Hospitals / ERs ---
  {
    id: 'loc-1',
    name: 'Grand River Hospital ER',
    type: 'hospital',
    latitude: 43.4516,
    longitude: -80.5052,
    address: '835 King St W, Kitchener',
    hours: '24/7',
    isOpen: true,
    waitMinutes: 120,
    services: ['Emergency care', 'Trauma', 'Imaging', 'Lab work', 'Pediatric ER'],
    isFree: true,
    phone: '519-749-4300',
    reports: [
      {
        id: 'rpt-1',
        facilityId: 'loc-1',
        reporterType: 'visitor',
        message: 'Wait was about 2 hours for non-urgent. Triage was quick though.',
        createdAt: '2026-03-14T08:30:00',
      },
      {
        id: 'rpt-2',
        facilityId: 'loc-1',
        reporterType: 'medical-professional',
        message: 'High volume tonight. Expect longer waits for CTAS 4-5.',
        strainLevel: 'high',
        waitTimeUpdate: 150,
        createdAt: '2026-03-14T02:15:00',
      },
    ],
  },
  {
    id: 'loc-2',
    name: "St. Mary's General Hospital ER",
    type: 'hospital',
    latitude: 43.4372,
    longitude: -80.4865,
    address: "911 Queen's Blvd, Kitchener",
    hours: '24/7',
    isOpen: true,
    waitMinutes: 95,
    services: ['Emergency care', 'Cardiac care', 'Imaging', 'Mental health crisis'],
    isFree: true,
    phone: '519-744-3311',
    reports: [
      {
        id: 'rpt-3',
        facilityId: 'loc-2',
        reporterType: 'visitor',
        message: 'Shorter wait than Grand River right now. Got seen in about 1.5 hours.',
        createdAt: '2026-03-14T10:00:00',
      },
    ],
  },
  {
    id: 'loc-3',
    name: 'Cambridge Memorial Hospital ER',
    type: 'hospital',
    latitude: 43.3616,
    longitude: -80.3144,
    address: '700 Coronation Blvd, Cambridge',
    hours: '24/7',
    isOpen: true,
    waitMinutes: 75,
    services: ['Emergency care', 'Imaging', 'Lab work'],
    isFree: true,
    phone: '519-621-2330',
    reports: [],
  },

  // --- Walk-in Clinics ---
  {
    id: 'loc-4',
    name: 'Kitchener Walk-In Clinic',
    type: 'walk-in',
    latitude: 43.4350,
    longitude: -80.5100,
    address: '525 Highland Rd W, Kitchener',
    hours: '8 AM – 8 PM',
    isOpen: true,
    closingTime: '8:00 PM',
    waitMinutes: 25,
    services: ['General assessment', 'Prescriptions', 'Blood work on-site'],
    isFree: true,
    reports: [],
  },
  {
    id: 'loc-5',
    name: 'Waterloo Walk-In Medical Centre',
    type: 'walk-in',
    latitude: 43.4680,
    longitude: -80.5250,
    address: '170 University Ave W, Waterloo',
    hours: '9 AM – 5 PM',
    isOpen: true,
    closingTime: '5:00 PM',
    waitMinutes: 35,
    services: ['General assessment', 'Prescriptions', 'Referrals'],
    isFree: true,
    reports: [],
  },
  {
    id: 'loc-6',
    name: 'UWaterloo Health Services',
    type: 'walk-in',
    latitude: 43.4723,
    longitude: -80.5449,
    address: 'SLC Building, Room 2040, Waterloo',
    hours: '9 AM – 4:30 PM',
    isOpen: true,
    closingTime: '4:30 PM',
    waitMinutes: 40,
    services: ['Student care', 'Mental health', 'Referrals', 'Immunizations'],
    isFree: true,
    reports: [],
  },

  // --- Urgent Care ---
  {
    id: 'loc-7',
    name: 'Grand River Urgent Care',
    type: 'urgent-care',
    latitude: 43.4820,
    longitude: -80.5460,
    address: '405 The Boardwalk, Waterloo',
    hours: '10 AM – 10 PM',
    isOpen: true,
    closingTime: '10:00 PM',
    waitMinutes: 45,
    services: ['Urgent assessment', 'X-ray', 'Stitches', 'Prescriptions'],
    isFree: true,
    reports: [],
  },

  // --- Community Health Centres (health & harm reduction focused) ---
  {
    id: 'loc-8',
    name: 'House of Friendship — Health Services',
    type: 'community-centre',
    latitude: 43.4480,
    longitude: -80.4900,
    address: '51 Charles St E, Kitchener',
    hours: '8:30 AM – 4:30 PM',
    isOpen: true,
    closingTime: '4:30 PM',
    services: ['Harm reduction services', 'Naloxone distribution', 'Addiction counselling', 'Supervised consumption', 'Wound care'],
    isFree: true,
    phone: '519-742-8327',
    resources: [
      { id: 'res-1', name: 'Naloxone kits (nasal)', category: 'harm-reduction', inStock: true, donationNeeded: false },
      { id: 'res-2', name: 'Naloxone kits (injectable)', category: 'harm-reduction', inStock: false, donationNeeded: true },
      { id: 'res-3', name: 'Sterile needle kits', category: 'harm-reduction', inStock: true, donationNeeded: false },
      { id: 'res-4', name: 'Fentanyl test strips', category: 'harm-reduction', inStock: true, donationNeeded: false },
      { id: 'res-5', name: 'Sharps disposal containers', category: 'harm-reduction', inStock: false, donationNeeded: true },
      { id: 'res-6', name: 'Wound care supplies', category: 'medical', inStock: true, donationNeeded: false },
      { id: 'res-7', name: 'Hygiene kits', category: 'hygiene', inStock: false, donationNeeded: true },
    ],
    reports: [
      {
        id: 'rpt-6',
        facilityId: 'loc-8',
        reporterType: 'medical-professional',
        message: 'Running low on injectable naloxone and sharps containers. Nasal Narcan still available.',
        createdAt: '2026-03-14T09:00:00',
      },
    ],
  },
  {
    id: 'loc-9',
    name: 'Sanguen Health Centre',
    type: 'community-centre',
    latitude: 43.4500,
    longitude: -80.4960,
    address: '150 Duke St W, Kitchener',
    hours: '9 AM – 5 PM',
    isOpen: true,
    closingTime: '5:00 PM',
    services: ['Harm reduction', 'Naloxone training', 'Needle exchange', 'Hepatitis C testing', 'HIV testing', 'Wound care'],
    isFree: true,
    phone: '519-603-0223',
    resources: [
      { id: 'res-8', name: 'Naloxone kits', category: 'harm-reduction', inStock: true, donationNeeded: false },
      { id: 'res-9', name: 'Sterile injection supplies', category: 'harm-reduction', inStock: true, donationNeeded: false },
      { id: 'res-10', name: 'Safer inhalation kits', category: 'harm-reduction', inStock: true, donationNeeded: false },
      { id: 'res-11', name: 'Hepatitis C rapid test kits', category: 'medical', inStock: true, donationNeeded: false },
      { id: 'res-12', name: 'HIV rapid test kits', category: 'medical', inStock: false, donationNeeded: true },
      { id: 'res-13', name: 'Wound care kits', category: 'medical', inStock: true, donationNeeded: false },
      { id: 'res-14', name: 'Condoms & dental dams', category: 'sexual-health', inStock: true, donationNeeded: false },
    ],
    reports: [],
  },
  {
    id: 'loc-10',
    name: 'Kitchener Downtown Community Health Centre',
    type: 'community-centre',
    latitude: 43.4490,
    longitude: -80.4930,
    address: '44 Francis St S, Kitchener',
    hours: '8 AM – 8 PM',
    isOpen: true,
    closingTime: '8:00 PM',
    services: ['Primary care', 'Harm reduction', 'Foot care', 'Chronic disease management', 'Health education', 'Prenatal care'],
    isFree: true,
    phone: '519-745-4404',
    resources: [
      { id: 'res-15', name: 'Menstrual products (pads & tampons)', category: 'hygiene', inStock: true, donationNeeded: false },
      { id: 'res-16', name: 'Prenatal vitamins', category: 'medical', inStock: false, donationNeeded: true },
      { id: 'res-17', name: 'Blood glucose monitors', category: 'medical', inStock: true, donationNeeded: false },
      { id: 'res-18', name: 'Naloxone kits', category: 'harm-reduction', inStock: true, donationNeeded: false },
      { id: 'res-19', name: 'Foot care supplies', category: 'medical', inStock: true, donationNeeded: false },
      { id: 'res-20', name: 'Condoms', category: 'sexual-health', inStock: true, donationNeeded: false },
      { id: 'res-21', name: 'Pregnancy tests', category: 'sexual-health', inStock: true, donationNeeded: false },
    ],
    reports: [
      {
        id: 'rpt-7',
        facilityId: 'loc-10',
        reporterType: 'medical-professional',
        message: 'Out of prenatal vitamins. Glucose monitors available. Menstrual products well-stocked.',
        createdAt: '2026-03-14T11:00:00',
      },
    ],
  },

  // --- Wellness Centres (mental health & primary care focused) ---
  {
    id: 'loc-11',
    name: 'Langs Community Health Centre',
    type: 'wellness-centre',
    latitude: 43.3890,
    longitude: -80.3700,
    address: '1145 Concession Rd, Cambridge',
    hours: '8:30 AM – 8 PM',
    isOpen: true,
    closingTime: '8:00 PM',
    services: ['Primary care', 'Mental health counselling', 'Diabetes education', 'Prenatal care', 'Dietitian', 'Sexual health clinic'],
    isFree: true,
    phone: '519-653-1470',
    resources: [
      { id: 'res-22', name: 'Mental health counselling slots', category: 'mental-health', inStock: true, donationNeeded: false },
      { id: 'res-23', name: 'Diabetes testing supplies', category: 'medical', inStock: true, donationNeeded: false },
      { id: 'res-24', name: 'Prenatal vitamins', category: 'medical', inStock: false, donationNeeded: true },
      { id: 'res-25', name: 'Menstrual products', category: 'hygiene', inStock: true, donationNeeded: false },
      { id: 'res-26', name: 'STI testing kits', category: 'sexual-health', inStock: true, donationNeeded: false },
      { id: 'res-27', name: 'Condoms & contraceptives', category: 'sexual-health', inStock: true, donationNeeded: false },
    ],
    reports: [],
  },
  {
    id: 'loc-12',
    name: 'KW Counselling Services',
    type: 'wellness-centre',
    latitude: 43.4505,
    longitude: -80.4880,
    address: '480 Charles St E, Kitchener',
    hours: '9 AM – 9 PM',
    isOpen: true,
    closingTime: '9:00 PM',
    services: ['Individual counselling', 'Family therapy', 'Group therapy', 'Crisis support', 'Sliding scale fees', 'Grief counselling'],
    isFree: false,
    phone: '519-884-0000',
    resources: [
      { id: 'res-28', name: 'Sliding scale therapy slots', category: 'mental-health', inStock: true, donationNeeded: false },
      { id: 'res-29', name: 'Free crisis walk-in sessions', category: 'mental-health', inStock: true, donationNeeded: false },
      { id: 'res-30', name: 'Group therapy sessions (anxiety)', category: 'mental-health', inStock: true, donationNeeded: false },
      { id: 'res-31', name: 'Group therapy sessions (grief)', category: 'mental-health', inStock: false, donationNeeded: false },
    ],
    reports: [],
  },
  {
    id: 'loc-13',
    name: 'Woolwich Community Health Centre',
    type: 'wellness-centre',
    latitude: 43.5370,
    longitude: -80.5580,
    address: '10 Parkside Dr, St. Jacobs',
    hours: '8:30 AM – 4:30 PM',
    isOpen: true,
    closingTime: '4:30 PM',
    services: ['Primary care', 'Mental health', 'Diabetes education', 'Nutrition counselling', 'Immunizations'],
    isFree: true,
    phone: '519-664-3794',
    resources: [
      { id: 'res-32', name: 'Flu vaccines', category: 'medical', inStock: true, donationNeeded: false },
      { id: 'res-33', name: 'Blood pressure monitors (loan)', category: 'medical', inStock: true, donationNeeded: false },
      { id: 'res-34', name: 'Menstrual products', category: 'hygiene', inStock: true, donationNeeded: false },
      { id: 'res-35', name: 'Mental health counselling slots', category: 'mental-health', inStock: false, donationNeeded: false },
    ],
    reports: [],
  },

  // --- Telehealth ---
  {
    id: 'loc-14',
    name: 'Maple Telehealth',
    type: 'telehealth',
    latitude: 43.4643,
    longitude: -80.5204,
    address: 'Online',
    hours: '24/7',
    isOpen: true,
    waitMinutes: 8,
    services: ['Video consult', 'Prescriptions', 'Specialist referral', 'Mental health'],
    isFree: false,
    reports: [],
  },
];
